CREATE TABLE IF NOT EXISTS role (
  id INT(10) UNSIGNED NOT NULL  AUTO_INCREMENT,
  name INT(10) UNSIGNED NOT NULL,              -- name of role
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
